// <auto-generated />
namespace Explorer.DataLayer.BreakAway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class FirstOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstOne));
        
        string IMigrationMetadata.Id
        {
            get { return "201501170438183_FirstOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
