TRUNCATE TABLE SalesLT.StatesReference

INSERT INTO SalesLT.StatesReference VALUES('Ontario','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Quebec','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Nova Scotia','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Brunswick','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Manitoba','Canada')
INSERT INTO SalesLT.StatesReference VALUES('British Columbia','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Prince Edward Island','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Saskatchewan','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Alberta','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Newfoundland','Canada')
INSERT INTO SalesLT.StatesReference VALUES('Alabama','US')
INSERT INTO SalesLT.StatesReference VALUES('Alaska','US')
INSERT INTO SalesLT.StatesReference VALUES('Arizona','US')
INSERT INTO SalesLT.StatesReference VALUES('Arkansas','US')
INSERT INTO SalesLT.StatesReference VALUES('California','US')
INSERT INTO SalesLT.StatesReference VALUES('Colorado','US')
INSERT INTO SalesLT.StatesReference VALUES('Connecticut','US')
INSERT INTO SalesLT.StatesReference VALUES('Delaware','US')
INSERT INTO SalesLT.StatesReference VALUES('Florida','US')
INSERT INTO SalesLT.StatesReference VALUES('Georgia','US')
INSERT INTO SalesLT.StatesReference VALUES('Hawaii','US')
INSERT INTO SalesLT.StatesReference VALUES('Idaho','US')
INSERT INTO SalesLT.StatesReference VALUES('Illinois','US')
INSERT INTO SalesLT.StatesReference VALUES('Indiana','US')
INSERT INTO SalesLT.StatesReference VALUES('Iowa','US')
INSERT INTO SalesLT.StatesReference VALUES('Kansas','US')
INSERT INTO SalesLT.StatesReference VALUES('Kentucky','US')
INSERT INTO SalesLT.StatesReference VALUES('Louisiana','US')
INSERT INTO SalesLT.StatesReference VALUES('Maine','US')
INSERT INTO SalesLT.StatesReference VALUES('Maryland','US')
INSERT INTO SalesLT.StatesReference VALUES('Massachusetts','US')
INSERT INTO SalesLT.StatesReference VALUES('Michigan','US')
INSERT INTO SalesLT.StatesReference VALUES('Minnesota','US')
INSERT INTO SalesLT.StatesReference VALUES('Mississippi','US')
INSERT INTO SalesLT.StatesReference VALUES('Missouri','US')
INSERT INTO SalesLT.StatesReference VALUES('Montana','US')
INSERT INTO SalesLT.StatesReference VALUES('Nebraska','US')
INSERT INTO SalesLT.StatesReference VALUES('Nevada','US')
INSERT INTO SalesLT.StatesReference VALUES('New Hampshire','US')
INSERT INTO SalesLT.StatesReference VALUES('New Jersey','US')
INSERT INTO SalesLT.StatesReference VALUES('New Mexico','US')
INSERT INTO SalesLT.StatesReference VALUES('New York','US')
INSERT INTO SalesLT.StatesReference VALUES('North Carolina','US')
INSERT INTO SalesLT.StatesReference VALUES('North Dakota','US')
INSERT INTO SalesLT.StatesReference VALUES('Ohio','US')
INSERT INTO SalesLT.StatesReference VALUES('Oklahoma','US')
INSERT INTO SalesLT.StatesReference VALUES('Oregon','US')
INSERT INTO SalesLT.StatesReference VALUES('Pennsylvania','US')
INSERT INTO SalesLT.StatesReference VALUES('Rhode Island','US')
INSERT INTO SalesLT.StatesReference VALUES('South Carolina','US')
INSERT INTO SalesLT.StatesReference VALUES('South Dakota','US')
INSERT INTO SalesLT.StatesReference VALUES('Tennessee','US')
INSERT INTO SalesLT.StatesReference VALUES('Texas','US')
INSERT INTO SalesLT.StatesReference VALUES('Utah','US')
INSERT INTO SalesLT.StatesReference VALUES('Vermont','US')
INSERT INTO SalesLT.StatesReference VALUES('Virginia','US')
INSERT INTO SalesLT.StatesReference VALUES('Washington','US')
INSERT INTO SalesLT.StatesReference VALUES('West Virginia','US')
INSERT INTO SalesLT.StatesReference VALUES('Wisconsin','US')
INSERT INTO SalesLT.StatesReference VALUES('Wyoming','US')
INSERT INTO SalesLT.StatesReference VALUES('England','England')
