//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explorer.DataLayer.AdventureWorks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksContext : DbContext
    {
        public AdventureWorksContext()
            : base("name=AdventureWorksContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Address> Addresses { get; set; }
        public IDbSet<Customer> Customers { get; set; }
        public IDbSet<CustomerAddress> CustomerAddresses { get; set; }
        public IDbSet<Product> Products { get; set; }
        public IDbSet<ProductCategory> ProductCategories { get; set; }
        public IDbSet<ProductDescription> ProductDescriptions { get; set; }
        public IDbSet<ProductModel> ProductModels { get; set; }
        public IDbSet<ProductModelProductDescription> ProductModelProductDescriptions { get; set; }
        public IDbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public IDbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
        public IDbSet<StatesReference> StatesReferences { get; set; }
    }
}
